[tool.poetry]
name = "training-blog"
version = "0.1.0"
description = ""
authors = ["Erica Williams <willieri@mail.nih.gov>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
